### ISSUE TITLE
Broadcast stops after sometime on 4g(mobile data)

### ISSUE THREAD

**Issue by vokal-suvajit** [WowzaMediaSystems/gocoder-sdk-samples-android#16]
I'm having this issue even on sample app also when I'm broadcasting using 4g(mobile data). Wifi its working fine. If needed I can provide full log from our production app.

Environment info:
Device - Xiaomi Mi4i (ferrari)
Android version - 5.0.2
Android api - 21

![device-2018-06-28-185027](https://user-images.githubusercontent.com/39044813/42036788-2f9a8e84-7b04-11e8-819d-0ff815a1acb1.png)

**Comment by vokal-suvajit** [comment]
**Error Log**

    06-28 11:47:25.504 13370-14503/com.oktalk.app E/d: A error occurred writing to the open broadcast connection
    java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
        at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
        at libcore.io.IoBridge.sendto(IoBridge.java:515)
        at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504)
        at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
        at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
        at com.wowza.gocoder.sdk.support.wse.d.f(GoCoderSDK:681)
        at com.wowza.gocoder.sdk.support.wse.d.a(GoCoderSDK:910)
        at com.wowza.gocoder.sdk.support.wse.d.a(GoCoderSDK:876)
        at com.wowza.gocoder.sdk.support.wse.c.onVideoFrame(GoCoderSDK:178)
        at com.wowza.gocoder.sdk.support.c.a$1.run(GoCoderSDK:687)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.system.ErrnoException: sendto failed: ECONNRESET (Connection reset by peer)
        at libcore.io.Posix.sendtoBytes(Native Method)
        at libcore.io.Posix.sendto(Posix.java:176)
        at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
        at libcore.io.IoBridge.sendto(IoBridge.java:513)
        at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504) 
        at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37) 
        at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266) 
        at com.wowza.gocoder.sdk.support.wse.d.f(GoCoderSDK:681) 
        at com.wowza.gocoder.sdk.support.wse.d.a(GoCoderSDK:910) 
        at com.wowza.gocoder.sdk.support.wse.d.a(GoCoderSDK:876) 
        at com.wowza.gocoder.sdk.support.wse.c.onVideoFrame(GoCoderSDK:178) 
        at com.wowza.gocoder.sdk.support.c.a$1.run(GoCoderSDK:687) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
    06-28 11:47:25.504 13370-14503/com.oktalk.app E/WZBroadcast: A broadcast component reported the following during the broadcast so it will be stopped
    severity                  : ERROR
    error class               : null
    error code                : 0
    description               : A error occurred writing to the open broadcast connection
    exception                 : java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
    06-28 11:47:25.504 13370-14503/com.oktalk.app E/GoLiveActivity: onError: A error occurred writing to the open broadcast connection
    06-28 11:47:25.504 13370-14477/com.oktalk.app D/GoLiveActivity: isStopping: 
    06-28 11:47:25.504 13370-14503/com.oktalk.app E/c: A error occurred writing to the open broadcast connection
    java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
        at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
        at libcore.io.IoBridge.sendto(IoBridge.java:515)
        at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504)
        at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
        at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
        at com.wowza.gocoder.sdk.support.wse.d.f(GoCoderSDK:681)
        at com.wowza.gocoder.sdk.support.wse.d.a(GoCoderSDK:910)
        at com.wowza.gocoder.sdk.support.wse.d.a(GoCoderSDK:876)
        at com.wowza.gocoder.sdk.support.wse.c.onVideoFrame(GoCoderSDK:178)
        at com.wowza.gocoder.sdk.support.c.a$1.run(GoCoderSDK:687)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.system.ErrnoException: sendto failed: ECONNRESET (Connection reset by peer)
        at libcore.io.Posix.sendtoBytes(Native Method)
        at libcore.io.Posix.sendto(Posix.java:176)
        at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
        at libcore.io.IoBridge.sendto(IoBridge.java:513)
        at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504) 
        at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37) 
        at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266) 
        at com.wowza.gocoder.sdk.support.wse.d.f(GoCoderSDK:681) 
        at com.wowza.gocoder.sdk.support.wse.d.a(GoCoderSDK:910) 
        at com.wowza.gocoder.sdk.support.wse.d.a(GoCoderSDK:876) 
        at com.wowza.gocoder.sdk.support.wse.c.onVideoFrame(GoCoderSDK:178) 
        at com.wowza.gocoder.sdk.support.c.a$1.run(GoCoderSDK:687) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by akeller** [comment]
Closing this as stale. If you are still experiencing the same issue with newer versions of the SDK and samples, please open a new issue.
