### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ber4444** [WowzaMediaSystems/gocoder-sdk-samples-android#30]
when clicking on "play a live stream":
```
2019-11-04 11:34:47.327 19161-19161/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wowza.gocoder.sdk.sampleapp, PID: 19161
    java.lang.RuntimeException: Unable to resume activity {com.wowza.gocoder.sdk.sampleapp/com.wowza.gocoder.sdk.sampleapp.PlayerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.wowza.gocoder.sdk.api.player.WOWZPlayerConfig.isAudioEnabled()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.wowza.gocoder.sdk.api.player.WOWZPlayerConfig.isAudioEnabled()' on a null object reference
        at com.wowza.gocoder.sdk.sampleapp.PlayerActivity.syncUIControlState(PlayerActivity.java:500)
        at com.wowza.gocoder.sdk.sampleapp.PlayerActivity.onResume(PlayerActivity.java:289)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
        at android.app.Activity.performResume(Activity.java:7939)
```
when clicking on "kotlin player":
```
2019-11-04 11:35:54.182 19285-19285/com.wowza.gocoder.sdk.sampleapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wowza.gocoder.sdk.sampleapp, PID: 19285
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wowza.gocoder.sdk.sampleapp/com.wowza.gocoder.sdk.sampleapp.KotlinPlayerActivity}: java.lang.IllegalStateException: WowzaGoCoder.getLastError() must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: WowzaGoCoder.getLastError() must not be null
        at com.wowza.gocoder.sdk.sampleapp.KotlinPlayerActivity.onCreate(KotlinPlayerActivity.kt:225)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
```

**Comment by fabio-delorenzo-wowza** [comment]
Hi ber4444,
did you add your own license key ?
what version of SDK are you using ?
Please, attach the full log.

Thanks

**Comment by ber4444** [comment]
I did add the license key in GoCoderSDKActivityBase.
It is the latest SDK I downloaded today.

**Comment by fabio-delorenzo-wowza** [comment]
Thanks for reporting that. Let me look into this issue.

**Comment by Wowza-Rose** [comment]
Can you please send me an email @ber4444 and give me the key you entered and exactly how you entered it? There have been some issues with people not entering the correct key from the right email.   Please do not post it in here as is it is your private key.  My email is rose.power@wowza.com

**Comment by ber4444** [comment]
done
