### ISSUE TITLE
Error during the IDLE to READY transition when starting a broadcast.

### ISSUE THREAD

**Issue by vladfargutu** [WowzaMediaSystems/gocoder-sdk-samples-android#4]
E/a: The connection attempt was refused by the remote destination or the destination could not be reached
                                                java.net.ConnectException: failed to connect to /xx.xx.xxx.xx (port 1935) after 8000ms: isConnected failed: ECONNREFUSED (Connection refused)
                                                    at libcore.io.IoBridge.isConnected(IoBridge.java:238)
                                                    at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
                                                    at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
                                                    at java.net.Socket.connect(Socket.java:882)
                                                    at com.wowza.gocoder.sdk.support.wse.b.c(GoCoderSDK:196)
                                                    at com.wowza.gocoder.sdk.support.wse.a.prepareForBroadcast(GoCoderSDK:161)
                                                    at com.wowza.gocoder.sdk.support.b.b$1.a(GoCoderSDK:194)
                                                    at com.wowza.gocoder.sdk.support.b.b$1.call(GoCoderSDK:181)
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                    at java.lang.Thread.run(Thread.java:818)
                                                 Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
                                                    at libcore.io.IoBridge.isConnected(IoBridge.java:223)
                                                    at libcore.io.IoBridge.connectErrno(IoBridge.java:171) 
                                                    at libcore.io.IoBridge.connect(IoBridge.java:122) 
                                                    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
                                                    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456) 
                                                    at java.net.Socket.connect(Socket.java:882) 
                                                    at com.wowza.gocoder.sdk.support.wse.b.c(GoCoderSDK:196) 
                                                    at com.wowza.gocoder.sdk.support.wse.a.prepareForBroadcast(GoCoderSDK:161) 
                                                    at com.wowza.gocoder.sdk.support.b.b$1.a(GoCoderSDK:194) 
                                                    at com.wowza.gocoder.sdk.support.b.b$1.call(GoCoderSDK:181) 
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                    at java.lang.Thread.run(Thread.java:818) 
E/b: A broadcast component reported the following error during the PREPARE_FOR_BROADCAST transition
                                                severity                  : ERROR
                                                error class               : WZStreamingError
                                                error code                : 60
                                                description               : The connection attempt was refused by the remote destination or the destination could not be reached
                                                exception                 : java.net.ConnectException: failed to connect to /xx.xx.xxx.xx (port 1935) after 8000ms: isConnected failed: ECONNREFUSED (Connection refused)
W/WZBroadcast: Ending the broadcast session due to an error that occurred during the IDLE to READY transition
E/GoCoderSDKFragmentBase: The connection attempt was refused by the remote destination or the destination could not be reached
                                                                     java.net.ConnectException: failed to connect to /xx.xx.xxx.xx (port 1935) after 8000ms: isConnected failed: ECONNREFUSED (Connection refused)
                                                                         at libcore.io.IoBridge.isConnected(IoBridge.java:238)
                                                                         at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
                                                                         at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                         at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                         at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
                                                                         at java.net.Socket.connect(Socket.java:882)
                                                                         at com.wowza.gocoder.sdk.support.wse.b.c(GoCoderSDK:196)
                                                                         at com.wowza.gocoder.sdk.support.wse.a.prepareForBroadcast(GoCoderSDK:161)
                                                                         at com.wowza.gocoder.sdk.support.b.b$1.a(GoCoderSDK:194)
                                                                         at com.wowza.gocoder.sdk.support.b.b$1.call(GoCoderSDK:181)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                      Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
                                                                         at libcore.io.IoBridge.isConnected(IoBridge.java:223)
                                  ...

**Comment by myoung1620** [comment]
It looks like the remote end rejected/refused the connection.  While you'd have to look into the media server you are connecting with to see why it's rejecting the request, we have looked at this error handling and should be updated in our next version.
